<div class="container">
	<div class="row">
		<div class="col-lg-4">			
			
			<img src="<?php base_url()?>public/images/Mythos.jpg" class="card-img-top" alt="...">
		</div>
		<div class="col-lg-8" style="color: white;">
			<p>The Cthulhu Mythos encompasses the shared elements, characters, settings, and themes found in the works of H.P. Lovecraft and associated horror fiction writers. Together, they form the mythos that authors writing in the Lovecraftian milieu have used — and continue to use — to craft their stories.The term itself was coined by the writer August Derleth. Although this legendarium is also sometimes called the Lovecraft Mythos, most notably by the Lovecraft scholar S.T. Joshi, it has long since moved beyond Lovecraft's original conception.

Robert M. Price, in his essay "H.P. Lovecraft and the Cthulhu Mythos", sees two stages in the development of the Cthulhu Mythos . The first stage, or "Cthulhu Mythos proper" as Price calls it, took shape during Lovecraft's lifetime and was subject to his guidance. The second stage occurred under August Derleth who attempted to categorize and expand the Mythos after Lovecraft's death, writer Richard L. Tierney later applied the term "Derleth Mythos" to distinguish between Lovecraft's works and Derleth's later stories.

During the latter part of Lovecraft's life, there was much borrowing of story elements among the authors of the "Lovecraft Circle", a clique of writers with whom Lovecraft corresponded. This group included Clark Ashton Smith, Robert E. Howard, Robert Bloch, Frank Belknap Long, Henry Kuttner and others.

Lovecraft recognized that each writer had his own story-cycle and that an element from one cycle would not necessarily become part of another simply because a writer used it in one of his stories. For example, although Smith might mention "Kthulhut" (Cthulhu) or Iog-Sotot (Yog-Sothoth) in one of his Hyperborean tales, this does not mean that Cthulhu is part of the Hyperborean cycle. A notable exception, however, is Smith's Tsathoggua, which Lovecraft appropriated for his revision of Zelia Bishop's "The Mound" (1940). Lovecraft effectively connected Smith's creation to his story-cycle by placing Tsathoggua alongside such entities as Tulu, Yig, Shub-Niggurath and Nug and Yeb in subterranean K'n-yan.

Most of the elements of Lovecraft's Mythos were not a cross-pollination of the various story-cycles of the Lovecraft Circle, but were instead deliberately created by each writer to become part of the Mythos — the most notable example being the various arcane grimoires of forbidden lore. So, for example, Robert E. Howard has his character Friedrich von Junzt reading Lovecraft's Necronomicon in "The Children of the Night" (1931), and Lovecraft in turn mentions Howard's Unaussprechlichen Kulten in both "Out of the Aeons" (1935) and "The Shadow Out of Time (1936).Howard frequently corresponded with H. P. Lovecraft, and the two would sometimes insert references or elements of each others' settings in their works. Later editors reworked many of the original Conan stories by Howard; thus, diluting this connection. Nevertheless, many of Howard's unedited Conan stories are arguably part of the Cthulhu Mythos.

The Mythos as a background elementEdit
According to David E. Schultz, Lovecraft never meant to create a canonical Mythos but rather intended his imaginary pantheon to serve merely as a background element. Thus, Lovecraft's "pseudomythology" — a term used by Lovecraft himself and others to describe the beings appearing in his stories — is the backdrop for his tales but is not the primary focus. Indeed, the cornerstone of his stories seems to be the town of Arkham and not beings like Cthulhu.

Furthermore, Lovecraft may not have been serious when he spoke of developing a "myth-cycle" and probably would have had no need to give it a name anyway. Since he used his Mythos simply as background material, he probably had this in mind when he allowed other writers to use it in their own stories. Moreover, it could be said that Lovecraft's Mythos was a kind of elaborate inside joke, propagating among the writers of his circle and wearing thin upon his death. Derleth seems to have not understood this and believed that Lovecraft wanted other authors to actively write about the myth-cycle rather than to simply allude to it in their stories.

"All my stories, as erotic as they may be, are based on the fundamental lore or legend that this world was inhabited at one time by another race who, in practicing black magic, lost their foothold and were expelled, yet live on outside ever ready to take possession of this earth again.”
- Harold Farnese, misquoting H.P. Lovecraft
The second stage began with August Derleth[6] who added to the mythos and developed the elemental system, associating the pantheon with the four elements: air, earth, fire and water. To understand the changes that Derleth made to Lovecraft's Mythos, it is important to distinguish among Lovecraft's stories. Price says that Lovecraft's writings can be divided into three separate groups: the Dunsanian, Arkham, and Cthulhu cycles.[3] The Dunsanian stories are those that are written in the vein of Lord Dunsany (and may include Lovecraft's so-called Dream Cycle tales), the Arkham stories include those that take place in Lovecraft's fictionalized New England setting, and the Cthulhu cycle stories are those that utilize Lovecraft's cosmic story-cycle (the Lovecraft Mythos).

Rather than distinguish among Lovecraft's various cycles, Derleth combined them, ignoring individual distinctions, to create a large, singular story-cycle. So, for example, Derleth appropriated Nodens from the Dunsanian cycle and leagued him with the Elder Gods against the Old Ones. Derleth also introduced a good versus evil dichotomy into the Mythos that was contrary to the dark, nihilistic vision of Lovecraft and his immediate circle.

Derleth further ignored any distinction between the story-cycles of Lovecraft and those of other writers. If Lovecraft referenced a name from another author, Derleth took that as justification to include the other author's story-cycle in the Cthulhu Mythos. For example, he developed Hastur into a Great Old One represented as an avatar by the King in Yellow of Robert W. Chambers from a passing reference linking Hastur and the Yellow Sign in Lovecraft's The Whisperer in Darkness.

Finally, Derleth apparently classified any story that mentioned a mythos element as belonging to the Cthulhu Mythos — consequently, any other element in the story also became part of the mythos. Hence, since Lovecraft made passing reference to Clark Ashton Smith's Book of Eibon, Derleth added Smith's Ubbo-Sathla to the mythos. Because of Derleth's broad canon, the Mythos would indeed grow enormously.

Further removing the Cthulhu Mythos from its source were stories written by such authors as Lin Carter, Colin Wilson, and Brian Lumley. Carter was especially influential in setting out detailed lists of gods, their ancestry, and their servitors through his Mythos tales, attempting to codify the elements of the Mythos as much as possible. Through this process, more gods, books, and places were created and interlinked with each other.

Another influence has been the Call of Cthulhu RPG published by Chaosium in 1981. Largely developed by Sandy Petersen, this version of the Mythos broke Lovecraft's entities down into further sub-groupings: Outer Gods, Great Old Ones, and the nebulously-termed Other Gods. Material from these sources has slowly crept back into mainstream Mythos fiction, as Chaosium published fiction related to, or written by players of the game.

Many of the newer generation of Mythos authors take their cue from this more clinical, continuity-focused brand of the Mythos instead of Lovecraft's more mysterious version.

However, as the Mythos has grown and it has become increasingly difficult for any one author to be familiar with all the elements, the Mythos can been seen as a series of interconnecting cycles of myth that sometimes conflict with one another. The Cycles include: The Cthulhu or Xothic Cycle; the Hastur Cycle; the Yog-Sothoth Cycle; the Tsathogguan or Hyperborean Cycle; the Yig Myth; the Yidhra Cycle; and the Legend of the Elder Gods. This would reflect the development of real myth, where conflicting versions of the same narrative exist as the legend spreads abroad and is elaborated upon. For example, tales about Gawain, Tristran, Lancelot, and Merlin had probably been stand-alone story cycles prior to falling into the "gravitational pull" of King Arthur legend (we know Lancelot was invented by Chretien de Troyes and was not in the original printed version of the legend). The advantage of this view is that it explains factual conflicts from story to story, avoiding the need for the kind of "smoothing out" that Lin Carter actively pursued.

The Mythos usually takes place in fictional New England towns and is centered on the Great Old Ones, a fearsome assortment of ancient, powerful deities who came from outer space and once ruled the Earth. They are presently quiescent, having fallen into a death-like sleep at some time in the distant past. The most well-known of these beings is Cthulhu, who currently lies "dead dreaming" in the submerged city of R'lyeh somewhere in the Southeast Pacific Ocean. One day, "when the stars are right", R'lyeh will rise from beneath the sea, and Cthulhu will awaken and wreak havoc on the earth.

Despite his notoriety, Cthulhu is not the most powerful of the deities, nor is he the theological center of the mythos. Instead, this position is held by the demon-god Azathoth, a mindless but all-powerful Outer God, ruling from his cosmically centered court. Nonetheless, his avatar Nyarlathotep, who fulfills Azathoth's random urges, has intervened more frequently and more directly in human affairs than any other Outer god. He has also displayed more blatant contempt for humanity, especially his own worshippers, than almost any other Lovecraftian deity.

The essence in the Mythos is that the human world and our role in it are an illusion. Humanity is living inside a fragile bubble of perception, unaware of what lies behind the curtains or even of the curtains themselves, and our seeming dominance over the world is illusory and ephemeral. We are blessed in that we do not realize what lies dormant in the unknown lurking places on Earth and beyond. As Lovecraft famously begins his short story, The Call of Cthulhu, "The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents."

Now and then, individuals can, by accident or carelessness, catch a glimpse of, or even confront the ancient extraterrestrial entities which the mythology centres around, usually with fatal consequences. Other times, they encounter by their non-human worshippers and servants, whose existence shatters the worldview of those who stumble across them. Human followers exist as well. Because of the limitations of the human mind, these deities appearances are so overwhelming that they can often drive a person insane. They are portrayed as neither good or evil; within the Mythos, these are concepts invented by our species as a way to explain what truly are inexplicable intentions and actions.

The Call of Cthulhu was the premiere story in which Lovecraft realized and made full use of these themes, which is why his mythology would later be named after the creature in this story, as it defined a new direction in both his authorship and in the horror fiction genre. This is also the first and only story by Lovecraft where humans and one of the cosmic entities called the Great Old Ones come face to face.

In his final years of writing, Lovecraft used fewer supernatural elements to represent the dangers which threaten humanity. Instead, he gradually replaced them with non-supernatural cosmic beings and phenomena, based on principles outside the laws of nature in our own space-time continuum. This sci-fi trend particularly becomes clear in works such as At the Mountains of Madness.</p>
		</div>
	</div>	
</div>